Adding FollowedUserCourses class
beyond-io/ClassRater pull request #53
Opened 2021-04-14 11:56 UTC by LeonRabinovich

This Resolves: #41

2021-04-14 15:07 UTC, ellaml approved these changes

2021-04-14 20:36 UTC, kobihk requested changes

2021-04-14 20:36 UTC, kobihk commented on homepage/models.py
> +        return f'user = {self.user}, cour = {self.course}'
```suggestion
        return f'user = {self.user}, course = {self.course}'

```

2021-04-15 07:08 UTC, LeonRabinovich commented on homepage/models.py
> +        return f'user = {self.user}, cour = {self.course}'
Changed

2021-04-17 09:55 UTC, oriAdler approved these changes

2021-04-17 19:40 UTC, kobihk approved these changes

2021-04-17 19:40 UTC, merged