Course model upd
beyond-io/ClassRater pull request #55
Opened 2021-04-19 14:17 UTC by VeraTs

Small update changing the mandatory field from `smallIntegerField` to `BooleanField`

2021-04-19 16:13 UTC, kobihk requested changes

2021-04-19 16:13 UTC, kobihk commented on homepage/models.py
> +        return f'prof = {self.professor_id}, cour = {self.course_id}'
```suggestion
        return f'professor_id = {self.professor_id}, course_id = {self.course_id}'

```

2021-04-19 16:20 UTC, ellaml approved these changes

2021-04-19 16:48 UTC, VeraTs commented on homepage/models.py
> +        return f'prof = {self.professor_id}, cour = {self.course_id}'
changed as requested

2021-04-19 18:29 UTC, LeonRabinovich approved these changes

2021-04-20 06:54 UTC, oriAdler approved these changes

2021-04-20 07:01 UTC, kobihk approved these changes

2021-04-20 07:02 UTC, merged