course methods and tests
beyond-io/ClassRater pull request #63
Opened 2021-04-22 13:45 UTC by VeraTs

Contains 2 new methods for the Course class:
- getDetails() // returns the details of the course as a list
- printDetails() // prints the details of the course in verbose form - intended for shell use

Also, added validation to 4 Course class fields:
- course_id >=1
- credits_points >=1
- num_of_raters >=0
- num_of_reviewers >= 0

Tests:
- create new single course
- call on getDetails() func
- call on printDetails() func
- exceptions for invalid input for the fields stated above
- create 2 new courses

fixes #57

2021-04-24 09:00 UTC, oriAdler commented on homepage/models.py
> +        validators=[MinValueValidator(0)])  # number of raters for course ratnig and course load
Typo in word ```rating``` in comment

2021-04-24 09:00 UTC, oriAdler commented on homepage/tests.py
> +    assert courses[0] == course
Can I suggest a different approach? ```assert Course.objects.filter(pk=course.id).exists()```
Pros: You don't have to retrieve all the course objects

2021-04-24 09:00 UTC, oriAdler commented on homepage/tests.py
> +    c1 = (1, "Linear Algebra 1", True, 4, "please contribute", 3.500, 4.000, 13, 7)
Suggested change ```c1``` --> ```course```

2021-04-24 09:00 UTC, oriAdler commented on homepage/tests.py
> +    c1 = (1, "Linear Algebra 1", True, 4, "please contribute", 3.500, 4.000, 13, 7)
Suggested change ```c1``` --> ```course```

2021-04-25 15:24 UTC, VeraTs commented on homepage/models.py
> +        validators=[MinValueValidator(0)])  # number of raters for course ratnig and course load
fixed

2021-04-25 15:50 UTC, oriAdler approved these changes

2021-04-25 15:51 UTC, ellaml approved these changes

2021-04-25 17:06 UTC, kobihk requested changes

2021-04-25 17:06 UTC, kobihk commented on homepage/models.py
> +        validators=[MinValueValidator(1)])  # the credit points assigned to this course by the college
maybe you can add max value validator

2021-04-25 17:06 UTC, kobihk commented on homepage/models.py
> +        msg = f'indentifier: {self.course_id}   \tName: {self.name}\nMandatory? {mandatory}\n'
```suggestion
        msg = f'Course identifier: {self.course_id}   \nName: {self.name}\nMandatory? {mandatory}\n'

```

2021-04-25 17:06 UTC, kobihk commented on homepage/models.py
> +        msg += f'Credit Points: {self.credit_points}\nSyllabi: {self.syllabi}\n'
instead of repeat "msg +=" you can do it with parenthesis like:
 msg = (
     f'indentifier: {self.course_id}   \tName: {self.name}\nMandatory? {mandatory}\n'
     f'Credit Points: {self.credit_points}\nSyllabi: {self.syllabi}\n'
     ...
)

2021-04-25 17:06 UTC, kobihk commented on homepage/models.py
> +        msg += f"{self.num_of_raters} Raters\nNumber Of Reviews: {self.num_of_reviewers}"
maybe instead of repeat "msg +=..." you can do it like:
```suggestion
        msg = (
            f"Course ID: {self.course_id}   \tName: {self.name}\nMandatory? {mandatory}\n"
            f"Credit Points: {self.credit_points}\nSyllabi: {self.syllabi}\n"
            f"Average Rating: {round(self.avg_rating, 3)} \tAverage Load: {round(self.avg_load, 3)}\t"
            f"{self.num_of_raters} Raters\nNumber Of Reviews: {self.num_of_reviewers}"
        )
```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_create_course():
please update:
```suggestion
def test_course_create_course():

```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_create_invalid_id_course():
please update
```suggestion
def test_course_create_invalid_id_course():

```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_create_invalid_num_raters_course():
please update:
```suggestion
def test_course_create_invalid_num_raters_course():

```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +    assert flag
I can see you have this code repeat many times maybe you can define all the valid values as constants and add help method that return the status for assert something like:
VALID_ID = 1
VALID_NAME = "Linear Algebra 1"
...

def check_validation(id=VALID_ID, name=VALID_NAME...., positive_test=True):
    # check input validation
    try:
        Course(id, name, mandatory, credit, syllabi, avg_load, avg_rating, num_raters, num_reviewers).clean_fields()
    except ValidationError:
        return not positive_test
    return positive_test

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_create_invalid_num_of_reviewers_course():
```suggestion
def test_course_create_invalid_num_of_reviewers_course():

```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_create_invalid_credit_course():
```suggestion
def test_course_create_invalid_credit_course():

```

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +    msg += "13 Raters\nNumber Of Reviews: 7\n"
same ^^ about repeat "msg +=" please use parenthesis instead

2021-04-25 17:06 UTC, kobihk commented on homepage/tests.py
> +def test_Course_get_details():
```suggestion
def test_course_get_details():

```

2021-04-25 20:33 UTC, VeraTs commented on homepage/models.py
> +        validators=[MinValueValidator(1)])  # the credit points assigned to this course by the college
As this is for credit points, and they are treated in various ways, I don't know what limit to put on it, for max.
There are two-semester labs that are 10 credits in some uni's, for example.

2021-04-25 21:18 UTC, VeraTs commented on homepage/tests.py
> +    assert flag
I took this under consideration, and after seeing what Ori did was inspired to use parametrize as well.

2021-04-26 07:02 UTC, kobihk requested changes

2021-04-26 07:02 UTC, kobihk commented on homepage/models.py
> +        validators=[MinValueValidator(1)])  # the credit points assigned to this course by the college
so maybe put something that can be max like 20 but it will not allow to add big numbers like 10000...

2021-04-26 07:02 UTC, kobihk commented on homepage/models.py
> +    def printDetails(self):
unlike java in python the convention is:
https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables
```suggestion
    def print_details(self):
```
please fix it for all the rest

2021-04-26 07:03 UTC, kobihk commented on homepage/tests.py
> +    assert flag
It looks great!!

2021-04-26 14:08 UTC, VeraTs commented on homepage/tests.py
> +    assert courses[0] == course
I decided to go with a get(pk=course.id) to make sure it exists, as the assert would catch the error

2021-04-26 14:12 UTC, VeraTs commented on homepage/models.py
> +    def printDetails(self):
changed it :)

2021-04-26 14:25 UTC, LeonRabinovich commented on homepage/tests.py
> +    assert courses[0] == course
I also think get is better than filter here.
filter returns a QuerySet of all items where (pk=course.id)

if you only need 1 item(and there should only be one) - its better to use objects.get

2021-04-26 16:28 UTC, kobihk approved these changes

2021-04-26 16:29 UTC, merged